stages:
  - trigger

EC2-DA_LM-Secure:
  stage: trigger
  trigger:
    include: EC2-DA_LM-Secure/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - EC2-DA_LM-Secure/*

EC2-DA_LM-UnSecure:
  stage: trigger
  trigger:
    include: EC2-DA_LM-UnSecure/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - EC2-DA_LM-UnSecure/*
